# Generated by Django 5.2.13 on 2026-05-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
