# Generated by Django 5.2.13 on 2026-05-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Present', max_length=10),
        ),
    ]
