# Generated by Django 5.2.13 on 2026-05-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_phone_student_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='student_faces/'),
        ),
    ]
