# Generated by Django 5.2.13 on 2026-05-06 10:38

import django.db.models.deletion
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_student_face_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='face_image',
        ),
        migrations.CreateModel(
            name='StudentFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=student.models.student_face_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='student.student')),
            ],
        ),
    ]
