# Generated by Django 5.2.13 on 2026-05-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_subject_class_name_subject_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='class_name',
        ),
    ]
