# Generated by Django 5.2.13 on 2026-06-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_attendanceevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='student.attendanceevidence'),
        ),
    ]
