# Generated by Django 5.2.13 on 2026-05-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_student_phone_student_profile_photo'),
        ('teacher', '0004_teacher_classes_teacher_department_teacher_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.AddField(
            model_name='teacher',
            name='departments',
            field=models.ManyToManyField(blank=True, to='student.department'),
        ),
    ]
